
# ===============================================================
# ========================= maven版本文件扫描 ! ===================
# ===============================================================
#需要扫描的关键字目录
rule:
  - luotao
  - wangj
#指定扫描特定后缀文件
suffix_match:
  - .java
#过滤指定后缀文件
suffix_filter:
  - .svn
  - .css
  - .jpg
  - .png
  - .gif
  - .setting
  - .project
  - .metadata
  - .plugins
  - .prefs
  - .ptlist
  - .MF
  - .swf
  - .sh
  - .dtd
  - .scc
  - .log
  - .lck
  - .zip
  - .php
  - .classes
  - .project
  - .jar
  - .dwt
  - .dnx
  - .xsl
